spring.application.name=fatecads

# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/fatecads_db
spring.datasource.username=postgres
spring.datasource.password=123456

# Atualização automática do esquema do banco de dados
spring.jpa.hibernate.ddl-auto=update

# Mostrar as consultas SQL no console
spring.jpa.properties.hibernate.format_sql=false

# Configuração da porta do servidor
server.port=8080