spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/fatecads_db
spring.datasource.username=postgres
spring.datasource.password=cnpj

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=false

server.port=8080

app.url=${APP_URL:http://localhost:8080}

spring.mail.host=${MAIL_HOST:}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
